# Generated by Django 5.0.5 on 2024-05-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoqueADS', '0002_categoria_produtos_criador_produtos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
